"""存储层：任务记录的 SQLite 持久化。"""

from .probe_store import ProbeRecord, ProbeStore
from .task_store import (
    DOWNGRADE_REASON_DISK_FAILURE,
    DOWNGRADE_REASON_UNKNOWN,
    DOWNGRADE_REASON_USER_CLEANED,
    DOWNGRADE_REASON_VOLUME_MIGRATED,
    DOWNGRADE_REASONS,
    RESOURCE_STATUS_AVAILABLE,
    RESOURCE_STATUS_MISSING,
    RESOURCE_STATUSES,
    STATUSES,
    TaskRecord,
    TaskStore,
)
from .translation_engine_store import (
    AVAILABILITY,
    DEFAULT_TRANSLATION_ENGINE_ID,
    ENGINE_TYPES,
    LOCAL_TRANSLATION_ENGINE_ID,
    LOCAL_TRANSLATION_ENGINE_NAME,
    LOCAL_TRANSLATION_MODEL,
    TranslationEngine,
    TranslationEngineStore,
)

__all__ = [
    "ProbeRecord",
    "ProbeStore",
    "TaskRecord",
    "TaskStore",
    "DOWNGRADE_REASON_DISK_FAILURE",
    "DOWNGRADE_REASON_UNKNOWN",
    "DOWNGRADE_REASON_USER_CLEANED",
    "DOWNGRADE_REASON_VOLUME_MIGRATED",
    "DOWNGRADE_REASONS",
    "RESOURCE_STATUS_AVAILABLE",
    "RESOURCE_STATUS_MISSING",
    "RESOURCE_STATUSES",
    "STATUSES",
    "AVAILABILITY",
    "DEFAULT_TRANSLATION_ENGINE_ID",
    "ENGINE_TYPES",
    "LOCAL_TRANSLATION_ENGINE_ID",
    "LOCAL_TRANSLATION_ENGINE_NAME",
    "LOCAL_TRANSLATION_MODEL",
    "TranslationEngine",
    "TranslationEngineStore",
]
