/* 共享常量：与后端状态机一致 */

export const STEPS = [
  { key: "DOWNLOADING", label: "下载" },
  { key: "EXTRACTING", label: "提取" },
  { key: "TRANSCRIBING", label: "识别" },
  { key: "TRANSLATING", label: "翻译" },
  { key: "BURNING", label: "烧录" },
];
export const STEP_KEYS = STEPS.map((s) => s.key);

export const STATUS_META = {
  PENDING: { label: "排队中", cls: "pending", icon: "ph-clock" },
  DOWNLOADING: { label: "下载视频", cls: "active", icon: "ph-spinner" },
  EXTRACTING: { label: "提取音频", cls: "active", icon: "ph-spinner" },
  TRANSCRIBING: { label: "语音识别", cls: "active", icon: "ph-spinner" },
  TRANSLATING: { label: "翻译字幕", cls: "active", icon: "ph-spinner" },
  BURNING: { label: "烧录字幕", cls: "active", icon: "ph-spinner" },
  SYNTHESIZING: { label: "生成配音", cls: "active", icon: "ph-spinner" },
  DUBBING: { label: "封装配音", cls: "active", icon: "ph-spinner" },
  SUCCESS: { label: "已完成", cls: "success", icon: "ph-check" },
  FAILED: { label: "失败", cls: "failed", icon: "ph-warning" },
  CANCELLED: { label: "已取消", cls: "failed", icon: "ph-stop-circle" },
};

export const LANG_LABEL = {
  auto: "自动检测",
  "zh-CN": "简体中文",
  "zh-TW": "繁体中文",
  zh: "中文",
  en: "英语",
  ja: "日语",
  ko: "韩语",
  es: "西班牙语",
  fr: "法语",
  de: "德语",
  ru: "俄语",
  it: "意大利语",
  pt: "葡萄牙语",
  vi: "越南语",
  th: "泰语",
  ar: "阿拉伯语",
  id: "印尼语",
  hi: "印地语",
  nl: "荷兰语",
  pl: "波兰语",
  tr: "土耳其语",
  sv: "瑞典语",
  uk: "乌克兰语",
  cs: "捷克语",
  da: "丹麦语",
  fi: "芬兰语",
  el: "希腊语",
  he: "希伯来语",
  hu: "匈牙利语",
  no: "挪威语",
  ro: "罗马尼亚语",
  sk: "斯洛伐克语",
  af: "南非荷兰语",
  ca: "加泰罗尼亚语",
  bg: "保加利亚语",
  hr: "克罗地亚语",
  ms: "马来语",
  fa: "波斯语",
  ur: "乌尔都语",
  bn: "孟加拉语",
  ta: "泰米尔语",
  sw: "斯瓦希里语",
};

export const TERMINAL = new Set(["SUCCESS", "FAILED", "CANCELLED"]);
